name: Airdrop
main: me.gregoryw.airdrop.Airdrop
version: 1.0
api-version: 1.13.2
commands:
    airdrop:
        aliases: [drop, ad, carepackage]
        description: Call in an airdrop!
        usage: /airdrop <kit name>